config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get '/home', to:  'pages#home'
	root 'pages#home'

	resources :recipes do
		member do
			post 'like'	
		end
	end

	resources :chefs, except: [:new]

	get '/register', to: 'chefs#new'

	get '/login', to: "logins#new"
	post '/login', to: "logins#create"
	get '/logout', to: "logins#destroy"

	resources :styles, only: [:new, :create, :show]
	resources :ingredients, only: [:new, :create, :show]
end

app/views/pages/home.html.erb
<div class ="center jumbotron">
<h1>Welcome to Recipe Portal</h1>
<h2>You will learn learn to cook</h2>

<%= link_to "Sign Up Now!", register_path, class: "bnt btn-lg btn-success" %>
</div>
<div class ="row" >
	<div class ="col-lg-4">
		<h3 class = "midrow">
			View Recipe as guest User
		</h3>
		<h2 class ="left" > Browse and view recipe as guest and Sign up later </h2>
		<p> <%= link_to "Browse Recipe Listings", recipes_path , class: "btn btn-warning btn-small" %></p>
	</div>
	<div class ="col-lg-4">
		<h3 class = "midrow">
			Sign In to Your Account
		</h3>
		<h2 class ="left" > Add/update your recipes/create reviews/like/dislike recipes & much more </h2>
		<p> <%= link_to "Log in to Your Account", login_path, class: "btn btn-warning btn-small" %></p>
	</div>
	<div class ="col-lg-4">
		<h3 class = "midrow">
			View Recipe as guest User
		</h3>
		<h2 class ="left" > Browse and view recipe as guest and Sign up later </h2>
		<p> <%= link_to "Browse Recipe Listings", "" , class: "btn btn-warning btn-small" %></p>
	</div>
	</div>